# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ibc_attestor import ibc_attestor_pb2 as ibc__attestor_dot_ibc__attestor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ibc_attestor/ibc_attestor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AttestationServiceStub(object):
    """Service definition for retrieving attestations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StateAttestation = channel.unary_unary(
                '/ibc_attestor.AttestationService/StateAttestation',
                request_serializer=ibc__attestor_dot_ibc__attestor__pb2.StateAttestationRequest.SerializeToString,
                response_deserializer=ibc__attestor_dot_ibc__attestor__pb2.StateAttestationResponse.FromString,
                _registered_method=True)
        self.PacketAttestation = channel.unary_unary(
                '/ibc_attestor.AttestationService/PacketAttestation',
                request_serializer=ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationRequest.SerializeToString,
                response_deserializer=ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationResponse.FromString,
                _registered_method=True)
        self.LatestHeight = channel.unary_unary(
                '/ibc_attestor.AttestationService/LatestHeight',
                request_serializer=ibc__attestor_dot_ibc__attestor__pb2.LatestHeightRequest.SerializeToString,
                response_deserializer=ibc__attestor_dot_ibc__attestor__pb2.LatestHeightResponse.FromString,
                _registered_method=True)


class AttestationServiceServicer(object):
    """Service definition for retrieving attestations.
    """

    def StateAttestation(self, request, context):
        """Retrieves an attestation for a state at a given height.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PacketAttestation(self, request, context):
        """Retrieves an attestation for a set of packets.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestHeight(self, request, context):
        """Returns the latest height of the attested chain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttestationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StateAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.StateAttestation,
                    request_deserializer=ibc__attestor_dot_ibc__attestor__pb2.StateAttestationRequest.FromString,
                    response_serializer=ibc__attestor_dot_ibc__attestor__pb2.StateAttestationResponse.SerializeToString,
            ),
            'PacketAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.PacketAttestation,
                    request_deserializer=ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationRequest.FromString,
                    response_serializer=ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationResponse.SerializeToString,
            ),
            'LatestHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestHeight,
                    request_deserializer=ibc__attestor_dot_ibc__attestor__pb2.LatestHeightRequest.FromString,
                    response_serializer=ibc__attestor_dot_ibc__attestor__pb2.LatestHeightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ibc_attestor.AttestationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ibc_attestor.AttestationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttestationService(object):
    """Service definition for retrieving attestations.
    """

    @staticmethod
    def StateAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ibc_attestor.AttestationService/StateAttestation',
            ibc__attestor_dot_ibc__attestor__pb2.StateAttestationRequest.SerializeToString,
            ibc__attestor_dot_ibc__attestor__pb2.StateAttestationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PacketAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ibc_attestor.AttestationService/PacketAttestation',
            ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationRequest.SerializeToString,
            ibc__attestor_dot_ibc__attestor__pb2.PacketAttestationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LatestHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ibc_attestor.AttestationService/LatestHeight',
            ibc__attestor_dot_ibc__attestor__pb2.LatestHeightRequest.SerializeToString,
            ibc__attestor_dot_ibc__attestor__pb2.LatestHeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
