# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ibc_attestor/ibc_attestor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ibc_attestor/ibc_attestor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import attestation_pb2 as ibc__attestor_dot_attestation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fibc_attestor/ibc_attestor.proto\x12\x0cibc_attestor\x1a\x1eibc_attestor/attestation.proto\")\n\x17StateAttestationRequest\x12\x0e\n\x06height\x18\x01 \x01(\x04\"J\n\x18StateAttestationResponse\x12.\n\x0b\x61ttestation\x18\x01 \x01(\x0b\x32\x19.ibc_attestor.Attestation\"r\n\x18PacketAttestationRequest\x12\x0f\n\x07packets\x18\x01 \x03(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x35\n\x0f\x63ommitment_type\x18\x03 \x01(\x0e\x32\x1c.ibc_attestor.CommitmentType\"K\n\x19PacketAttestationResponse\x12.\n\x0b\x61ttestation\x18\x01 \x01(\x0b\x32\x19.ibc_attestor.Attestation\"\x15\n\x13LatestHeightRequest\"&\n\x14LatestHeightResponse\x12\x0e\n\x06height\x18\x01 \x01(\x04*b\n\x0e\x43ommitmentType\x12\x1a\n\x16\x43OMMITMENT_TYPE_PACKET\x10\x00\x12\x17\n\x13\x43OMMITMENT_TYPE_ACK\x10\x01\x12\x1b\n\x17\x43OMMITMENT_TYPE_RECEIPT\x10\x02\x32\xb4\x02\n\x12\x41ttestationService\x12\x61\n\x10StateAttestation\x12%.ibc_attestor.StateAttestationRequest\x1a&.ibc_attestor.StateAttestationResponse\x12\x64\n\x11PacketAttestation\x12&.ibc_attestor.PacketAttestationRequest\x1a\'.ibc_attestor.PacketAttestationResponse\x12U\n\x0cLatestHeight\x12!.ibc_attestor.LatestHeightRequest\x1a\".ibc_attestor.LatestHeightResponseB\x10Z\x0etypes/attestorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc_attestor.ibc_attestor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016types/attestor'
  _globals['_COMMITMENTTYPE']._serialized_start=456
  _globals['_COMMITMENTTYPE']._serialized_end=554
  _globals['_STATEATTESTATIONREQUEST']._serialized_start=81
  _globals['_STATEATTESTATIONREQUEST']._serialized_end=122
  _globals['_STATEATTESTATIONRESPONSE']._serialized_start=124
  _globals['_STATEATTESTATIONRESPONSE']._serialized_end=198
  _globals['_PACKETATTESTATIONREQUEST']._serialized_start=200
  _globals['_PACKETATTESTATIONREQUEST']._serialized_end=314
  _globals['_PACKETATTESTATIONRESPONSE']._serialized_start=316
  _globals['_PACKETATTESTATIONRESPONSE']._serialized_end=391
  _globals['_LATESTHEIGHTREQUEST']._serialized_start=393
  _globals['_LATESTHEIGHTREQUEST']._serialized_end=414
  _globals['_LATESTHEIGHTRESPONSE']._serialized_start=416
  _globals['_LATESTHEIGHTRESPONSE']._serialized_end=454
  _globals['_ATTESTATIONSERVICE']._serialized_start=557
  _globals['_ATTESTATIONSERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
