# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from relayer import relayer_pb2 as relayer_dot_relayer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relayer/relayer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayerServiceStub(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RelayByTx = channel.unary_unary(
                '/relayer.RelayerService/RelayByTx',
                request_serializer=relayer_dot_relayer__pb2.RelayByTxRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.RelayByTxResponse.FromString,
                _registered_method=True)
        self.CreateClient = channel.unary_unary(
                '/relayer.RelayerService/CreateClient',
                request_serializer=relayer_dot_relayer__pb2.CreateClientRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.CreateClientResponse.FromString,
                _registered_method=True)
        self.UpdateClient = channel.unary_unary(
                '/relayer.RelayerService/UpdateClient',
                request_serializer=relayer_dot_relayer__pb2.UpdateClientRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.UpdateClientResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/relayer.RelayerService/Info',
                request_serializer=relayer_dot_relayer__pb2.InfoRequest.SerializeToString,
                response_deserializer=relayer_dot_relayer__pb2.InfoResponse.FromString,
                _registered_method=True)


class RelayerServiceServicer(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    def RelayByTx(self, request, context):
        """Relay the ibc packets produced by the results of transactions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateClient(self, request, context):
        """Create a new ibc client on the target (destination) chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClient(self, request, context):
        """Update the ibc client on the target (destination) chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Request relayer information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RelayByTx': grpc.unary_unary_rpc_method_handler(
                    servicer.RelayByTx,
                    request_deserializer=relayer_dot_relayer__pb2.RelayByTxRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.RelayByTxResponse.SerializeToString,
            ),
            'CreateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClient,
                    request_deserializer=relayer_dot_relayer__pb2.CreateClientRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.CreateClientResponse.SerializeToString,
            ),
            'UpdateClient': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClient,
                    request_deserializer=relayer_dot_relayer__pb2.UpdateClientRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.UpdateClientResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=relayer_dot_relayer__pb2.InfoRequest.FromString,
                    response_serializer=relayer_dot_relayer__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relayer.RelayerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relayer.RelayerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayerService(object):
    """The relayer service definition
    Each relayer service is defined between two chains.
    One chain is the source chain, and the other chain is the target chain.
    """

    @staticmethod
    def RelayByTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relayer.RelayerService/RelayByTx',
            relayer_dot_relayer__pb2.RelayByTxRequest.SerializeToString,
            relayer_dot_relayer__pb2.RelayByTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relayer.RelayerService/CreateClient',
            relayer_dot_relayer__pb2.CreateClientRequest.SerializeToString,
            relayer_dot_relayer__pb2.CreateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relayer.RelayerService/UpdateClient',
            relayer_dot_relayer__pb2.UpdateClientRequest.SerializeToString,
            relayer_dot_relayer__pb2.UpdateClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relayer.RelayerService/Info',
            relayer_dot_relayer__pb2.InfoRequest.SerializeToString,
            relayer_dot_relayer__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
